exports.Cluster = '172.23.120.87'
exports.RBACUser = "Administrator";
exports.RBACKPassword = "esabhcuoc";
exports.DefaultBucket = 'test_eventing'
exports.AuthPassword = ''
// exports.Buckets = ['server', 'sdk', 'mobile']
exports.Buckets = []
exports.httpListen = '172.23.120.87'
exports.httpPort = 80
exports.httpsPort = 443
exports.Certificate = '/root/certs/wildcard.sc.couchbase.com-2025/e2462cad8794b9b0.pem'
exports.PrivateKey = '/root/certs/wildcard.sc.couchbase.com-2025/privatekey.pem'